apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app
  version: 2.2.0
  repo: http://chartmuseum-private.chartmuseum-private.svc.cluster.local:8080/
  valuesFile: values.yaml
  namespace: staging-worker-validate-order-created
  releaseName: worker-validate-order-created
