apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: worker
  version: 1.0.1
  repo: http://chartmuseum-private.chartmuseum-private.svc.cluster.local:8080/
  valuesFile: values.yaml
  namespace: worker-upload-img
  releaseName: worker-upload-img
