apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: app
  version: 2.2.0
  repo: http://chartmuseum-private.chartmuseum-private.svc.cluster.local:8080/
  valuesFile: values.yaml
  namespace: access-route-cd-api
  releaseName: access-route-cd-api
