replicaCount: 1
image:
  repository: igrowdigital/access-route-cd-api
  pullPolicy: IfNotPresent
  tag: commit-881ddd3b7
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceMonitor:
  enabled: true
  namespace: monitoring
serviceAccount:
  create: false
  # annotations: {}
  # name: ""
podDisruptionBudget:
  enabled: false
  minAvailable: 1
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: selfsigned
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
  - host: api.anota-ai.com
    paths:
    - path: /noauth/access(/|$)(.*)
probes:
  enabled: true
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "200"
env: null
nodeSelector: {}
tolerations: []
affinity: {}
redis:
  install: false
serviceMonitor:
  enabled: true
  namespace: monitoring
command:
- node
- app.js
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
podDisruptionBudget:
  enabled: true
  minAvailable: 1
ports:
- name: http
  containerPort: 1232
  protocol: TCP
- name: metrics
  containerPort: 8080
  protocol: TCP
